package com.example.cs125final;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.animation.Animation;
import android.view.animation.AnimationUtils;
import android.widget.Button;
import android.widget.TextView;

public class Credits extends AppCompatActivity {

    protected Button back;
    protected TextView credits;
    private Animation animation;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_credits);
        credits = findViewById(R.id.creditList);
        back = findViewById(R.id.backToMenu);
        animation = AnimationUtils.loadAnimation(getApplicationContext(), R.anim.creditscroll);
        final Intent toMenu = new Intent(Credits.this, StartScreen.class);
        back.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startActivity(toMenu);
            }
        });
        credits.setText("CREDITS\n\n\n"
                + "The Professor:\n\n\nGeoff Challen\n\n\n"
                + "The Head CAs:\n\nBen Nordick\n"
                + "Amirtha Sureshbabu\n"
                + "Daniel Gleason\n"
                + "Max Kopinsky\n\n\n"
                + "The Teaching Assistants:\n\n\n"
                + "Beichen Zhang\n"
                + "Bruno Seo\n"
                + "Heather Huynh\n"
                + "Hyo Jin (Gina) Do\n"
                + "Jishnu Dey\n"
                + "Mingkun Gao\n"
                + "Sneha Krishna Kumaran\n"
                + "Zhenyi Tang\n\n\n"
                + "Office Hour Captains:\n\n\n"
                + "Ajay Tatachar\n"
                + "Hyosang Ahn\n"
                + "Long Phan\n"
                + "Long Phan\n"
                + "Nikhil Garg\n"
                + "Rima Bouhal\n\n\n"
                + "Course Associates:\n\n\n"
                + "Blair Wang\n"
                + "David Ruvinskiy\n"
                + "Lou Zeh\n"
                + "Mat Farley\n"
                + "Ruisong Li\n\n\n"
                + "Course Assistants:\n\n\n"
                + "Aaditya Dhruv\n"
                + "Aasik Pazhani\n"
                + "Adarsh Suresh\n"
                + "Aileen Long\n"
                + "Akshit Deshpande\n"
                + "Albert Chen\n"
                + "Alexa Hu\n"
                + "Alexander Marcozzi\n"
                + "Andrea Roy\n"
                + "Angela Zhao\n"
                + "Annie Li\n"
                + "Annmay Sharma\n"
                + "Arnav Batta\n"
                + "Bhavesh Prahladka\n"
                + "Boda Song\n"
                + "Bohan Liu\n"
                + "Bojiang Li\n"
                + "Chengyang Song\n"
                + "Chenhui Zhang\n"
                + "Chiao Ting Huang\n"
                + "Chris Kull\n"
                + "Christina Hu\n"
                + "Cindia Hua\n"
                + "Da'mon Morris\n"
                + "David Ngo\n"
                + "Dev Wadhwa\n"
                + "Dhruv Agrawal\n"
                + "Dhruv Rajgarhia\n"
                + "Eesha Moona\n"
                + "Elias Hadgu\n"
                + "Evelyn Yang\n"
                + "Fantah Kabba\n"
                + "Felicia Wang\n"
                + "Frank Yang\n"
                + "Geoffrey Ma\n"
                + "Hania Dziurdzik\n"
                + "Haoyu Liu\n"
                + "Harry Liang\n"
                + "Hui Yu\n"
                + "Ishita Rao\n"
                + "Jack Shao\n"
                + "Jacob Rubin\n"
                + "Jiale Ning\n"
                + "Jiawei Pei\n"
                + "John Wei\n"
                + "Kanav Bhatnagar\n"
                + "Kanav Khanna\n"
                + "Kinlung Seetho\n"
                + "Manasi Abhyankar\n"
                + "Martin Beczkiewicz\n"
                + "Matt Forrest\n"
                + "Matt Geimer\n"
                + "Matthew Larson\n"
                + "Meera Jagannathan\n"
                + "Megha Ganesh\n"
                + "Melissa Cho\n"
                + "Michelle Liang\n"
                + "Mickey Leung\n"
                + "Nathan Omerza\n"
                + "Nathaniel Zukowski\n"
                + "Nikhil Richard\n"
                + "Nikil Ravi\n"
                + "Parth Tyagi\n"
                + "Peiyuan Jin\n"
                + "Peizhe Liu\n"
                + "Pengwei Zang\n"
                + "Pengyue Jiang\n"
                + "Raghav Saini\n"
                + "Renzo Marc Ledesma\n"
                + "Rohit Mullappalli\n"
                + "Saket Vissapragada\n"
                + "Sam Li\n"
                + "Sarod Nori\n"
                + "Sean Koo\n"
                + "Shirley Mao\n"
                + "Shiven Kumar\n"
                + "Shreya Sharma\n"
                + "Shruthi Jaganathan\n"
                + "Sicong He\n"
                + "Sid Pothuganti\n"
                + "Siddhesh Agarwal\n"
                + "Snehal Somalraju\n"
                + "Sreenidhi Vijayaraghavan\n"
                + "Sruthi Kilari\n"
                + "Sujit Varadhan\n"
                + "Tanvi Chadha\n"
                + "Teresa Dong\n"
                + "Toby Sinclair\n"
                + "Tongli Zhou\n"
                + "Toorno Mishra\n"
                + "Viola Zhao\n"
                + "Wei Xia\n"
                + "William Nawor\n"
                + "William Zhao\n"
                + "Xinshuo Lei\n"
                + "Yashovardhan Maheshwari\n"
                + "Yijie Huang\n"
                + "Yucheng Feng\n"
                + "Yucheng Jiang\n"
                + "Yueqi Jiang\n"
                + "Yufei Zhu\n"
                + "Yufeng Liu\n"
                + "Yuhan Lu\n"
                + "Yuheng Ding\n"
                + "Yuqing Su\n"
                + "Zachary Mattingly\n"
                + "Zhanyi Lin\n"
                + "Zhuofan Jia\n\n\n"
                + "The Course Developers:\n\n\n"
                + "Adam Zhao\n"
                + "Angie Cheng\n"
                + "Aniket Gargya\n"
                + "Anush Sandeep\n"
                + "Arjun V. Nair\n"
                + "Filip Matasic\n"
                + "Gabriella Xue\n"
                + "Harshit Bagla\n"
                + "Nehal Singh\n"
                + "Peiyan Wu\n"
                + "Rithvik Mahindra\n"
                + "Satwik Singh\n"
                + "Varnit Sinha\n"
                + "Veeresh Neralagi\n"
                + "Zihan Xu\n\n\n\n"
                + "Thank you to every one of you! If a single one of you were missing, "
                + "CS125 wouldn't have been the awesome experience that it was!!\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
                + "Massive thanks to\n"
                + "Martin, David, Lou, Daniel, Ben, and Geoff for participating in our game!\n\n\n"
                + "Game made by:\n\n"
                + "Thomas Constertina and Nathan Grace"
        );
        credits.startAnimation(animation);
    }
}
